[en]
  languageName = "English"
  languageCode = "en"
  weight = 1
  title = "J. Alonso Guerra"
  [en.params]
    tagline = "Golang Backend Engineer | Cloud Architect"

[es]
  languageName = "Espa√±ol"
  languageCode = "es"
  weight = 2
  title = "J. Alonso Guerra"
  [es.params]
    tagline = "Ingeniero Backend Golang | Arquitecto Cloud"
