toc = true
avatar = "img/commons/avatar.jpg"
author = "jalonso"

[assets]
  self_host = false

[social]
  name = "J. Alonso Guerra"
  url = "https://github.com/j-alonso-guerra"

[[social.links]]
  type = "github"
  id = "j-alonso-guerra"
  icon = "fab fa-github"

[[social.links]]
  type = "linkedin"
  id = "j-alonso-guerra"
  icon = "fab fa-linkedin"

[[social.links]]
  type = "email"
  id = "juniorguerrac17@gmail.com"
  icon = "fas fa-envelope"

[[social.links]]
  type = "rss"
  icon = "fas fa-rss"
  noblank = true

[comments]
  enable = false
  provider = ""
